spring:
  application:
    name: RoutingDataSourceProject
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver

datasource1:
  url: jdbc:postgresql://localhost:5433/routingdb-1
  username: postgres
  password: root

datasource2:
  url: jdbc:postgresql://localhost:5434/routingdb-2
  username: postgres
  password: root

springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoint:
    info:
      enable: true