spring:
  application:
    name: RoutingDataSourceProject

  datasource:
    url: jdbc:postgresql://localhost:5433/routingdb-1
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver

  datasource2:
    url: jdbc:postgresql://localhost:5434/routingdb-2
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


springdoc:
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoint:
    info:
      enable: true